=== otmanoulcaid/montainer/backend/app/src/data/xml/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="password" type="xs:string"/>

                            <xs:element name="role">
                                <xs:complexType>
                                    <xs:attribute name="typeRole" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="eng"/>
                                                <xs:enumeration value="tech"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>

                            <xs:element name="job">
                                <xs:complexType>
                                    <xs:attribute name="typeJob" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="technicien"/>
                                                <xs:enumeration value="ingenieur"/>
                                                <xs:enumeration value="chef_projet"/>
                                                <xs:enumeration value="manager"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                        <xs:attribute name="id" type="xs:ID" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== otmanoulcaid/montainer/backend/app/src/data/xml/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="users.xsd">

  <user id="u10">
    <name>Aymane</name>
    <password>test</password>
    <role typeRole="devops"/> <!--devops | tech-->
    <job typeJob="chef_projet"/> <!--technicien | ingenieur | chef_projet | manager -->
  </user>

  <user id="u11">
    <name>Otman</name>
    <password>test</password>
    <role typeRole="tech"/>
    <job typeJob="ingenieur"/>
  </user>

  <user id="u12">
    <name>Houssam</name>
    <password>test</password>
    <role typeRole="devops"/>
    <job typeJob="manager"/>
  </user>

  <user id="u13">
    <name>Khalid</name>
    <password>test</password>
    <role typeRole="tech"/>
    <job typeJob="manager"/>
  </user>

</users>
